# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in wcc-contentful.gemspec
gemspec

gem 'wcc-contentful', path: File.expand_path('../wcc-contentful', __dir__)
