# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in wcc-contentful.gemspec
gemspec

gem 'wcc-contentful', path: File.expand_path('../wcc-contentful', __dir__)
