---
exclude:
  # SVG images rendered in erb templates
  # Special script that needs to break the rules
linters:
  AllowedScriptType:
    enabled: true
    disallow_inline_scripts: true
  ErbSafety:
    enabled: true
    exclude:
      # TODO: find a better way to generate the HTML
      # https://github.com/watermarkchurch/wcc-contentful/issues/104
      - '**/app/views/sections/_video*.html.erb'
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  RightTrim:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
