sudo: false
language: ruby
cache:
  directories:
    - /tmp/vendor/bundle
    - node_modules
rvm:
  - 2.3.8
  - 2.5.3
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/middleman_4.2.gemfile
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install: gem install bundler -v 1.17.3
install:
  - bin/use
  - bundle install --path /tmp/vendor/bundle
  - bin/bundle install --path /tmp/vendor/bundle
script:
  - export COVERALLS_PARALLEL=true
  - bin/bundle exec rspec --format documentation --order rand
jobs:
  exclude:
    rvm: 2.3.8
    gemfile: gemfiles/middleman_4.2.gemfile
  include:
    - stage: coverage
      script:
        - bundle exec rake coverage
        - bundle exec rake coverage:coveralls
      # Keep in mind to overwrite these here
      rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
    - stage: lint
      before_script:
        - npm install
      script:
        - bundle exec danger
        - bundle exec rubocop
        - bundle exec erblint '*/app/views/**/*.erb'
        - npm run lint
      # Keep in mind to overwrite these here
      rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
notifications:
  webhooks: https://coveralls.io/webhook