sudo: false
language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_install: gem install bundler -v 1.16.1
install:
  - bin/bundle install --path /tmp/vendor/bundle
script:
  - export COVERALLS_PARALLEL=true
  - bin/rspec --format documentation
notifications:
  webhooks: https://coveralls.io/webhook