sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_install: gem install bundler -v 1.16.1
install:
  - bin/bundle install --path /tmp/vendor/bundle
before_script:
  - bundle exec danger
script:
  - export COVERALLS_PARALLEL=true
  - bin/rspec --format documentation --order rand
  - bundle exec rubocop
  - bundle exec erblint '*/app/views/**/*.erb'
notifications:
  webhooks: https://coveralls.io/webhook