sudo: false
language: ruby
cache:
  directories:
    - /tmp/vendor/bundle
    - node_modules
rvm:
  - 2.3.8
  - 2.5.3
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.0.gemfile
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install: gem install bundler -v 1.16.1
install:
  - bundle install --path /tmp/vendor/bundle
script:
  - export COVERALLS_PARALLEL=true
  - bin/bundle exec rspec --format documentation --order rand
  # only run coverage on the wcc-contentful gem
  - bundle exec rake wcc-contentful:coverage
jobs:
  include:
    - stage: lint
      before_script:
        - npm install
      script:
        - bundle exec danger
        - bundle exec rubocop
        - bundle exec erblint '*/app/views/**/*.erb'
        - npm run lint
      # Keep in mind to overwrite these here
      rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
notifications:
  webhooks: https://coveralls.io/webhook