sudo: false
language: ruby
cache:
  directories:
    - /tmp/vendor/bundle
rvm:
  - 2.3.8
  - 2.5.3
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.0.gemfile
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_install: gem install bundler -v 1.16.1
install:
  - bundle install --path /tmp/vendor/bundle
script:
  - export COVERALLS_PARALLEL=true
  - bin/bundle exec rspec --format documentation --order rand
jobs:
  include:
    - stage: lint
      script:
        - bundle exec danger
        - bundle exec rubocop
        - bundle exec erblint '*/app/views/**/*.erb'
      # Keep in mind to overwrite these here
      rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
notifications:
  webhooks: https://coveralls.io/webhook