sudo: false
language: ruby
cache:
  directories:
    - /tmp/vendor/bundle
    - node_modules
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install: gem install bundler -v 1.17.3
install:
  - bin/use
  - bundle install --path /tmp/vendor/bundle
  - bin/bundle install --path /tmp/vendor/bundle
script:
  - export COVERALLS_PARALLEL=true
  - bin/bundle exec rspec --format documentation --order rand
jobs:
  include:
    - rvm: 2.5.7
      gemfile: gemfiles/rails_5.2_ruby_2.5.7.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_5.2_ruby_2.3.8.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails_5.0_ruby_2.5.7.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_5.0_ruby_2.3.8.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/middleman_4.2_ruby_2.5.7.gemfile
    - stage: coverage
      script:
        - bundle exec rake coverage
        - bundle exec rake coverage:coveralls
      # Keep in mind to overwrite these here
      rvm: 2.5.7
      gemfile: gemfiles/rails_5.2_ruby_2.5.7.gemfile
    - stage: lint
      before_script:
        - npm install
      script:
        - bundle exec danger
        - bundle exec rubocop
        - bundle exec erblint '*/app/views/**/*.erb'
        - npm run lint
      # Keep in mind to overwrite these here
      rvm: 2.5.7
      gemfile: gemfiles/rails_5.2_ruby_2.5.7.gemfile
notifications:
  webhooks: https://coveralls.io/webhook