# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/http-form_data/all/http-form_data.rbi
#
# http-form_data-1.0.3
module HTTP
end
module HTTP::FormData
  def self.create(data); end
  def self.ensure_hash(obj); end
  def self.multipart?(data); end
end
class HTTP::FormData::Part
  def content_type; end
  def filename; end
  def initialize(body, opts = nil); end
  def size; end
  def to_s; end
end
class HTTP::FormData::File < HTTP::FormData::Part
  def initialize(file_or_io, opts = nil); end
  def mime_type; end
  def size; end
  def to_s; end
  def with_io; end
end
class HTTP::FormData::Multipart
  def content_length; end
  def content_type; end
  def glue; end
  def head; end
  def initialize(data); end
  def tail; end
  def to_s; end
end
class HTTP::FormData::Multipart::Param
  def initialize(name, value); end
  def self.coerce(data); end
  def size; end
  def to_s; end
end
class HTTP::FormData::Urlencoded
  def content_length; end
  def content_type; end
  def initialize(data); end
  def to_s; end
end
class HTTP::FormData::Error < StandardError
end
