# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/wcc-base/all/wcc-base.rbi
#
# wcc-base-0.3.1
module WCC
end
class WCC::Railties < Rails::Railtie
end
