version: 2.1

executors:
  ruby:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.version >>-node
        environment:
          POSTGRES_CONNECTION: postgresql://ubuntu:test@127.0.0.1:5432/circle_ruby_test
      - image: postgres:10
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: test
          POSTGRES_DB: circle_ruby_test

jobs:
  lint:
    parameters:
      ruby:
        type: string
      gemfile:
        type: string
    executor:
      name: ruby
      version: << parameters.ruby >>
    environment:
      BUNDLE_PATH: ~/vendor/bundle
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout

      - run:
          name: Check if any specs have "focus"
          command: |
            [[ -z "$(find . -type f -name \*_spec.rb | xargs grep -e ':focus' -e 'focus: true')" ]]
      - run:
          name: Install Gems
          command: |
            bin/use
            bundle install
            bin/bundle install
      - run:
          name: Coverage
          command: |
            bin/bundle exec rspec
            bundle exec rake coverage:coveralls
      - run:
          name: Lint
          command: |
            bundle exec danger
            bundle exec rubocop
            bundle exec erblint '*/app/views/**/*.erb'
            npm install
            npm run lint

  test:
    parameters:
      ruby:
        type: string
      gemfile:
        type: string
    executor:
      name: ruby
      version: << parameters.ruby >>
    environment:
      BUNDLE_PATH: ~/vendor/bundle
      BUNDLE_GEMFILE: << parameters.gemfile >>
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - run:
          name: Install Gems
          command: |
            bin/use
            bundle install
            bin/bundle install
      - run:
          name: Run Tests
          command: |
            bin/bundle exec rspec --format documentation --order rand

workflows:
  build:
    jobs:
      - test:
          name: test_rails-6.1_ruby-2.7.6
          ruby: 2.7.6
          gemfile: gemfiles/rails_6.1_ruby_2.7.6.gemfile
      - test:
          name: test_rails-6.1_ruby-3.1
          ruby: 3.1.1
          gemfile: gemfiles/rails_6.1_ruby_3.1.gemfile
      - test:
          name: test_rails-7.0_ruby-3.2
          ruby: 3.2.2
          gemfile: gemfiles/rails_7.0_ruby_3.2.gemfile
      - test:
          name: test_middleman-4.2_ruby-2.7.6
          ruby: 2.7.6
          gemfile: gemfiles/middleman_4.2_ruby_2.7.6.gemfile

      - lint: 
          ruby: 2.7.6
          gemfile: gemfiles/rails_7.0_ruby_3.2.gemfile
          requires:
            - test_rails-7.0_ruby-3.2


